In [37]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import r2_score

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

import joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
iris_data = load_iris()
X_data = iris_data["data"]
y_data = iris_data["target"]

X_train, X_test, y_train, y_test = train_test_split(X_data, y_data, random_state=42)
# print(X_train.shape)
# print(X_test.shape)
# print(y_train.shape)
# print(y_test.shape)

k_n_neibours = KNeighborsClassifier(n_neighbors=1)
k_n_neibours.fit(X_train, y_train)

#path_for_model = "C:\\Users\\NCC\\Documents\\Ra Ma Dan\\ML Pro\\My_Models"
path_for_model = "C:\\Users\\NCC\\Documents\\Ra Ma Dan\\ML Pro\\My_Models\\iris_predic_model.pkl"
#joblib.dump("iris_predic_model.pkl", "..//..//My_Models")
#joblib.dump(k_n_neibours, path_for_model)

In [36]:
iris = pd.DataFrame(X_train, columns=iris_data.feature_names)
#grr = plt.scatter(iris, c=y_train, figsize=(15, 15), marker="o", hist_kwds={"bins": 20}, s=60, alph=0.8)
iris.head()
prediction = k_n_neibours.predict(X_test)
prediction
r2 = r2_score(prediction, y_test)
np_mean = np.mean(prediction == y_test)
knn_score = k_n_neibours.score(X_test, y_test)
knn_train = k_n_neibours.score(X_train, y_train)
prediction

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [10]:
print(f"r2_score: {r2 * 100:.2f}")
print(f"np_mean: {np_mean * 100:.2f}")
print(f"knn_score: {knn_score * 100:.2f}")
print(f"knn_train: {knn_train * 100:.2f}")

r2_score: 100.00
np_mean: 100.00
knn_score: 100.00
knn_train: 100.00


In [38]:
dec_tree = DecisionTreeClassifier()
dec_tree.fit(X_train, y_train)

prediction = dec_tree.predict(X_test)
prediction
r2 = r2_score(prediction, y_test)
np_mean = np.mean(prediction == y_test)
knn_score = k_n_neibours.score(X_test, y_test)
knn_train = k_n_neibours.score(X_train, y_train)
prediction

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [39]:
print(f"r2_score: {r2 * 100:.2f}")
print(f"np_mean: {np_mean * 100:.2f}")
print(f"knn_score: {knn_score * 100:.2f}")
print(f"knn_train: {knn_train * 100:.2f}")

r2_score: 100.00
np_mean: 100.00
knn_score: 100.00
knn_train: 100.00


In [40]:
rand_forest = RandomForestClassifier()
rand_forest.fit(X_train, y_train)

prediction = rand_forest.predict(X_test)
prediction
r2 = r2_score(prediction, y_test)
np_mean = np.mean(prediction == y_test)
knn_score = k_n_neibours.score(X_test, y_test)
knn_train = k_n_neibours.score(X_train, y_train)

In [41]:
print(f"r2_score: {r2 * 100:.2f}")
print(f"np_mean: {np_mean * 100:.2f}")
print(f"knn_score: {knn_score * 100:.2f}")
print(f"knn_train: {knn_train * 100:.2f}")

r2_score: 100.00
np_mean: 100.00
knn_score: 100.00
knn_train: 100.00


In [43]:
print(f" X_data {X_data}\n\n")
print(f" X_test {X_test}\n\n")
print(f" y_test {y_test}")
prediction

 X_data [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [42]:
sv_mod = SVC()
sv_mod.fit(X_train, y_train)

prediction = sv_mod.predict(X_test)
prediction
r2 = r2_score(prediction, y_test)
np_mean = np.mean(prediction == y_test)
knn_score = k_n_neibours.score(X_test, y_test)
knn_train = k_n_neibours.score(X_train, y_train)
prediction

print(f"r2_score: {r2 * 100:.2f}")
print(f"np_mean: {np_mean * 100:.2f}")
print(f"knn_score: {knn_score * 100:.2f}")
print(f"knn_train: {knn_train * 100:.2f}")

r2_score: 100.00
np_mean: 100.00
knn_score: 100.00
knn_train: 100.00
